/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

import com.mycompany.modules.DatabaseUtility;
import com.mycompany.modules.UserAuthenticator;
import com.mycompany.modules.tables.Accounts;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
/** 
 *
 * @author Dane Aldritch Datuin
 */
public class AccountInformationPage extends javax.swing.JFrame {
    private Accounts loggedAccount;

    public AccountInformationPage() {
        initComponents();
    }

    public AccountInformationPage(Accounts user) {
        initComponents();
        this.loggedAccount = user;
        fetchAccountInfo();
        addEditListeners();
        addHomeTabListener();
        addLogoutListener();    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPane = new javax.swing.JLayeredPane();
        AccountTabShape = new wastemanagement.components.RoundedPanel();
        AccountLabel = new javax.swing.JLabel();
        AccountIcon = new javax.swing.JLabel();
        InfoTabShape = new wastemanagement.components.RoundedPanel();
        InfoTab = new javax.swing.JLabel();
        InfoLabel = new javax.swing.JLabel();
        InfoIcon = new javax.swing.JLabel();
        MapTabShape = new wastemanagement.components.RoundedPanel();
        MapTab = new javax.swing.JLabel();
        MapLabel = new javax.swing.JLabel();
        MapIcon = new javax.swing.JLabel();
        ContentSection = new wastemanagement.components.RoundedPanel();
        SearchBarShape = new wastemanagement.components.RoundedPanel();
        SearchBar = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JLabel();
        EnterIcon = new javax.swing.JLabel();
        AccountNameLbl = new javax.swing.JLabel();
        ContactNoShape = new wastemanagement.components.RoundedPanel();
        ContactNumberTxt = new javax.swing.JLabel();
        EditContactIcon = new javax.swing.JLabel();
        EditEmailIcon1 = new javax.swing.JLabel();
        EmailAdShape = new wastemanagement.components.RoundedPanel();
        EmailAdTxt = new javax.swing.JLabel();
        EditEmailIcon = new javax.swing.JLabel();
        EditEmailIcon2 = new javax.swing.JLabel();
        IdeasTableShape = new wastemanagement.components.RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IdeasTableContainer = new wastemanagement.components.RoundedPanel();
        row = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        ItemName = new javax.swing.JLabel();
        ItemName1 = new javax.swing.JLabel();
        EditIdea = new javax.swing.JLabel();
        RemoveIdea = new javax.swing.JLabel();
        ItemNoColLbl = new javax.swing.JLabel();
        ImageColLbl = new javax.swing.JLabel();
        ItemNameColLbl = new javax.swing.JLabel();
        LogoutTxt = new javax.swing.JLabel();
        LogoutIcon = new javax.swing.JLabel();
        EditNameIcon = new javax.swing.JLabel();
        HomeTabShape = new wastemanagement.components.RoundedPanel();
        HomeTab = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1024));

        BackgroundPane.setBackground(new java.awt.Color(85, 136, 59));
        BackgroundPane.setOpaque(true);

        AccountTabShape.setBackground(new java.awt.Color(230, 240, 220));
        AccountTabShape.setRoundTopLeft(60);
        AccountTabShape.setRoundTopRight(60);
        AccountTabShape.setLayout(null);

        AccountLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountLabel.setText("Account");
        AccountTabShape.add(AccountLabel);
        AccountLabel.setBounds(70, 20, 110, 40);

        AccountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person.png"))); // NOI18N
        AccountTabShape.add(AccountIcon);
        AccountIcon.setBounds(20, 20, 40, 40);

        BackgroundPane.setLayer(AccountTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(AccountTabShape);
        AccountTabShape.setBounds(780, 30, 200, 100);

        InfoTabShape.setBackground(new java.awt.Color(193, 232, 153));
        InfoTabShape.setRoundTopLeft(60);
        InfoTabShape.setRoundTopRight(60);
        InfoTabShape.setLayout(null);

        InfoTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        InfoTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoTab);
        InfoTab.setBounds(0, 0, 200, 60);

        InfoLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        InfoLabel.setText("Info");
        InfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoLabel);
        InfoLabel.setBounds(100, 10, 62, 40);

        InfoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Info.png"))); // NOI18N
        InfoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoIcon);
        InfoIcon.setBounds(40, 10, 40, 40);

        BackgroundPane.setLayer(InfoTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(InfoTabShape);
        InfoTabShape.setBounds(300, 50, 200, 100);

        MapTabShape.setBackground(new java.awt.Color(193, 232, 153));
        MapTabShape.setRoundTopLeft(60);
        MapTabShape.setRoundTopRight(60);
        MapTabShape.setLayout(null);

        MapTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        MapTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MapTabShape.add(MapTab);
        MapTab.setBounds(0, 0, 200, 60);

        MapLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        MapLabel.setText("Map");
        MapTabShape.add(MapLabel);
        MapLabel.setBounds(100, 10, 60, 40);

        MapIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/location.png"))); // NOI18N
        MapTabShape.add(MapIcon);
        MapIcon.setBounds(40, 10, 40, 40);

        BackgroundPane.setLayer(MapTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(MapTabShape);
        MapTabShape.setBounds(540, 50, 200, 100);

        ContentSection.setBackground(new java.awt.Color(230, 240, 220));
        ContentSection.setRoundTopLeft(60);
        ContentSection.setRoundTopRight(60);
        ContentSection.setLayout(null);

        SearchBarShape.setBackground(new java.awt.Color(217, 217, 217));
        SearchBarShape.setRoundBottomLeft(50);
        SearchBarShape.setRoundBottomRight(50);
        SearchBarShape.setRoundTopLeft(50);
        SearchBarShape.setRoundTopRight(50);
        SearchBarShape.setLayout(null);

        SearchBar.setBackground(new java.awt.Color(217, 217, 217));
        SearchBar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(128, 128, 128));
        SearchBar.setText("Search your recycling ideas");
        SearchBar.setBorder(null);
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBarShape.add(SearchBar);
        SearchBar.setBounds(40, 0, 530, 40);

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-Small.png"))); // NOI18N
        SearchBarShape.add(SearchIcon);
        SearchIcon.setBounds(10, 0, 20, 40);

        EnterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Right Arrow-Small.png"))); // NOI18N
        EnterIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBarShape.add(EnterIcon);
        EnterIcon.setBounds(580, 0, 20, 40);

        ContentSection.add(SearchBarShape);
        SearchBarShape.setBounds(210, 190, 620, 40);

        AccountNameLbl.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountNameLbl.setText("[Account Owner Full Name]");
        ContentSection.add(AccountNameLbl);
        AccountNameLbl.setBounds(340, 80, 370, 40);

        ContactNoShape.setBackground(new java.awt.Color(193, 232, 153));
        ContactNoShape.setRoundBottomLeft(40);
        ContactNoShape.setRoundBottomRight(40);
        ContactNoShape.setRoundTopLeft(40);
        ContactNoShape.setRoundTopRight(40);
        ContactNoShape.setLayout(null);

        ContactNumberTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactNumberTxt.setText("[Contact Number]");
        ContactNoShape.add(ContactNumberTxt);
        ContactNumberTxt.setBounds(40, 0, 230, 30);

        EditContactIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-small.png"))); // NOI18N
        EditContactIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContactNoShape.add(EditContactIcon);
        EditContactIcon.setBounds(270, 0, 30, 30);

        EditEmailIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phone-fill.png"))); // NOI18N
        EditEmailIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContactNoShape.add(EditEmailIcon1);
        EditEmailIcon1.setBounds(10, 0, 26, 30);

        ContentSection.add(ContactNoShape);
        ContactNoShape.setBounds(530, 140, 300, 30);

        EmailAdShape.setBackground(new java.awt.Color(193, 232, 153));
        EmailAdShape.setRoundBottomLeft(40);
        EmailAdShape.setRoundBottomRight(40);
        EmailAdShape.setRoundTopLeft(40);
        EmailAdShape.setRoundTopRight(40);
        EmailAdShape.setLayout(null);

        EmailAdTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailAdTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailAdTxt.setText("[Email Address]");
        EmailAdShape.add(EmailAdTxt);
        EmailAdTxt.setBounds(40, 0, 230, 30);

        EditEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-small.png"))); // NOI18N
        EditEmailIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmailAdShape.add(EditEmailIcon);
        EditEmailIcon.setBounds(270, 0, 30, 30);

        EditEmailIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail-fill.png"))); // NOI18N
        EditEmailIcon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmailAdShape.add(EditEmailIcon2);
        EditEmailIcon2.setBounds(10, 0, 27, 30);

        ContentSection.add(EmailAdShape);
        EmailAdShape.setBounds(210, 140, 300, 30);

        IdeasTableShape.setBackground(new java.awt.Color(193, 232, 153));
        IdeasTableShape.setRoundTopLeft(80);
        IdeasTableShape.setRoundTopRight(80);
        IdeasTableShape.setLayout(null);

        IdeasTableContainer.setBackground(new java.awt.Color(159, 201, 102));
        IdeasTableContainer.setLayout(null);

        row.setBackground(new java.awt.Color(183, 222, 137));
        row.setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(image);
        image.setBounds(0, 0, 180, 120);

        row.add(jPanel1);
        jPanel1.setBounds(158, 0, 178, 120);

        ItemName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName.setText("[Item Name]");
        row.add(ItemName);
        ItemName.setBounds(340, 40, 320, 30);

        ItemName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName1.setText("[Item Name]");
        row.add(ItemName1);
        ItemName1.setBounds(0, 40, 160, 30);

        EditIdea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-small.png"))); // NOI18N
        EditIdea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        row.add(EditIdea);
        EditIdea.setBounds(680, 40, 30, 30);

        RemoveIdea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-small.png"))); // NOI18N
        RemoveIdea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        row.add(RemoveIdea);
        RemoveIdea.setBounds(740, 40, 30, 30);

        IdeasTableContainer.add(row);
        row.setBounds(0, 0, 780, 120);

        jScrollPane1.setViewportView(IdeasTableContainer);

        IdeasTableShape.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 790, 340);

        ItemNoColLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ItemNoColLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemNoColLbl.setText("Item No.");
        IdeasTableShape.add(ItemNoColLbl);
        ItemNoColLbl.setBounds(30, 0, 124, 30);

        ImageColLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ImageColLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageColLbl.setText("Image");
        IdeasTableShape.add(ImageColLbl);
        ImageColLbl.setBounds(200, 0, 124, 30);

        ItemNameColLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ItemNameColLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemNameColLbl.setText("Item Name");
        IdeasTableShape.add(ItemNameColLbl);
        ItemNameColLbl.setBounds(460, 0, 124, 30);

        ContentSection.add(IdeasTableShape);
        IdeasTableShape.setBounds(100, 240, 830, 380);

        LogoutTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutTxt.setText("Log out");
        ContentSection.add(LogoutTxt);
        LogoutTxt.setBounds(930, 20, 70, 30);

        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log-out.png"))); // NOI18N
        LogoutIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContentSection.add(LogoutIcon);
        LogoutIcon.setBounds(890, 15, 30, 40);

        EditNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-medium.png"))); // NOI18N
        EditNameIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContentSection.add(EditNameIcon);
        EditNameIcon.setBounds(720, 80, 30, 40);

        BackgroundPane.setLayer(ContentSection, javax.swing.JLayeredPane.POPUP_LAYER);
        BackgroundPane.add(ContentSection);
        ContentSection.setBounds(0, 110, 1040, 620);

        HomeTabShape.setBackground(new java.awt.Color(193, 232, 153));
        HomeTabShape.setRoundTopLeft(60);
        HomeTabShape.setRoundTopRight(60);
        HomeTabShape.setLayout(null);

        HomeTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeTabShape.add(HomeTab);
        HomeTab.setBounds(0, 0, 200, 60);

        HomeLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeLabel.setText("Home");
        HomeTabShape.add(HomeLabel);
        HomeLabel.setBounds(90, 10, 80, 40);

        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        HomeTabShape.add(HomeIcon);
        HomeIcon.setBounds(30, 10, 40, 40);

        BackgroundPane.setLayer(HomeTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(HomeTabShape);
        HomeTabShape.setBounds(50, 50, 200, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed
    
    private void fetchAccountInfo() {
        AccountNameLbl.setText(loggedAccount.getFullName());
        EmailAdTxt.setText(loggedAccount.getEmail());
        ContactNumberTxt.setText(loggedAccount.getContactInfo());
    }

    private void addHomeTabListener() {
        HomeTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HomePage homePage = new HomePage(loggedAccount);
                homePage.setLocationRelativeTo(null);
                homePage.setVisible(true);
                dispose();
            }
        });
    }

    private void addLogoutListener() {
        LogoutIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                    null,
                    "Are you sure you want to logout?",
                    "Confirm Logout",
                    JOptionPane.YES_NO_OPTION);
                
                if (confirm == JOptionPane.YES_OPTION) {
                    LoginPage loginPage = new LoginPage();
                    loginPage.setLocationRelativeTo(null);
                    loginPage.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    private void addEditListeners() {
        EditNameIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String newName = JOptionPane.showInputDialog(null, 
                    "Enter new name:", "Edit Name", JOptionPane.PLAIN_MESSAGE);

                if(newName == null || newName.trim().isEmpty()) 
                {
                    JOptionPane.showMessageDialog(null, "Empty input for name!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(UserAuthenticator.updateAccount("name", newName, loggedAccount.getAccID()))
                {
                    AccountNameLbl.setText(newName);
                }
                
            }
        });

        EditEmailIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String newEmail = JOptionPane.showInputDialog(null, 
                    "Enter new email:", "Edit Email", JOptionPane.PLAIN_MESSAGE);

                if(newEmail == null || newEmail.trim().isEmpty()) 
                {
                    JOptionPane.showMessageDialog(null, "Empty input for email!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if (!newEmail.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                    JOptionPane.showMessageDialog(null, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if(UserAuthenticator.updateAccount("email", newEmail, loggedAccount.getAccID()))
                {
                    EmailAdTxt.setText(newEmail);
                }
            }
        });

        EditContactIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String newContact = JOptionPane.showInputDialog(null, 
                    "Enter new contact number:", "Edit Contact", JOptionPane.PLAIN_MESSAGE);

                if(newContact == null || newContact.trim().isEmpty()) 
                {
                    JOptionPane.showMessageDialog(null, "Empty input for contact information!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(UserAuthenticator.updateAccount("contact_info", newContact, loggedAccount.getAccID()))
                {
                    ContactNumberTxt.setText(newContact);
                }
            }
        });

        HomeTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HomePage homePage = new HomePage(loggedAccount);
                homePage.setLocationRelativeTo(null);
                homePage.setVisible(true);
                dispose();
            }
        });

        InfoTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GeneralInformationPage infoPage = new GeneralInformationPage();
                infoPage.setLocationRelativeTo(null);
                infoPage.setVisible(true);
                dispose();
            }
        });

        MapTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                MapPage mapPage = new MapPage();
                mapPage.setLocationRelativeTo(null);
                mapPage.setVisible(true);
                dispose();
            }
        });

        LogoutIcon.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                    null,
                    "Are you sure you want to logout?",
                    "Confirm Logout",
                    JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    LoginPage loginPage = new LoginPage();
                    loginPage.setLocationRelativeTo(null);
                    loginPage.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            JOptionPane.showMessageDialog(null, 
                "Please login first to view account information.", 
                "Login Required", 
                JOptionPane.WARNING_MESSAGE);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountIcon;
    private javax.swing.JLabel AccountLabel;
    private javax.swing.JLabel AccountNameLbl;
    private wastemanagement.components.RoundedPanel AccountTabShape;
    private javax.swing.JLayeredPane BackgroundPane;
    private wastemanagement.components.RoundedPanel ContactNoShape;
    private javax.swing.JLabel ContactNumberTxt;
    private wastemanagement.components.RoundedPanel ContentSection;
    private javax.swing.JLabel EditContactIcon;
    private javax.swing.JLabel EditEmailIcon;
    private javax.swing.JLabel EditEmailIcon1;
    private javax.swing.JLabel EditEmailIcon2;
    private javax.swing.JLabel EditIdea;
    private javax.swing.JLabel EditNameIcon;
    private wastemanagement.components.RoundedPanel EmailAdShape;
    private javax.swing.JLabel EmailAdTxt;
    private javax.swing.JLabel EnterIcon;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel HomeTab;
    private wastemanagement.components.RoundedPanel HomeTabShape;
    private wastemanagement.components.RoundedPanel IdeasTableContainer;
    private wastemanagement.components.RoundedPanel IdeasTableShape;
    private javax.swing.JLabel ImageColLbl;
    private javax.swing.JLabel InfoIcon;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel InfoTab;
    private wastemanagement.components.RoundedPanel InfoTabShape;
    private javax.swing.JLabel ItemName;
    private javax.swing.JLabel ItemName1;
    private javax.swing.JLabel ItemNameColLbl;
    private javax.swing.JLabel ItemNoColLbl;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel LogoutTxt;
    private javax.swing.JLabel MapIcon;
    private javax.swing.JLabel MapLabel;
    private javax.swing.JLabel MapTab;
    private wastemanagement.components.RoundedPanel MapTabShape;
    private javax.swing.JLabel RemoveIdea;
    private javax.swing.JTextField SearchBar;
    private wastemanagement.components.RoundedPanel SearchBarShape;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel row;
    // End of variables declaration//GEN-END:variables
}
