/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

import com.mycompany.components.CustomScrollbar.ScrollBarCustom;
import com.mycompany.modules.tables.Accounts;
import com.mycompany.modules.tables.WasteItems;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import wastemanagement.components.RoundedPanel;

/**
 *
 * @author Datuin
 */
public class AddOrEdit extends javax.swing.JFrame {

    private ArrayList<JPanel> itemPanelCollection = new ArrayList<JPanel>();
    private ArrayList<JPanel> stepPanelCollection = new ArrayList<JPanel>();
    
    private String fromWhere = null;
    private WasteItems foundItem = null;
    private List<WasteItems> items = null;
    private Accounts loggedAccount = null;
    
    
    public AddOrEdit() {
        initComponents();
        
        itemPanelCollection.add(jPanel3);
        stepPanelCollection.add(jPanel6);
        ScrollBarCustom newScrollBar1 = new ScrollBarCustom();
        newScrollBar1.setForeground(new Color(85, 136, 59));
        ScrollBarCustom newScrollBar2 = new ScrollBarCustom();
        newScrollBar2.setForeground(new Color(85, 136, 59));
        jScrollPane3.setVerticalScrollBar(newScrollBar1);
        jScrollPane1.setVerticalScrollBar(newScrollBar2);
    }
    
    public AddOrEdit(WasteItems selectedItem, List<WasteItems> itemsList, Accounts user, String origin) {
        this.fromWhere = origin;
        this.foundItem = selectedItem;
        this.items = itemsList;
        this.loggedAccount = user;
        
        initComponents();
        
        itemPanelCollection.add(jPanel3);
        stepPanelCollection.add(jPanel6);
        ScrollBarCustom newScrollBar1 = new ScrollBarCustom();
        newScrollBar1.setForeground(new Color(85, 136, 59));
        ScrollBarCustom newScrollBar2 = new ScrollBarCustom();
        newScrollBar2.setForeground(new Color(85, 136, 59));
        jScrollPane3.setVerticalScrollBar(newScrollBar1);
        jScrollPane1.setVerticalScrollBar(newScrollBar2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPane = new javax.swing.JLayeredPane();
        ContentSection = new wastemanagement.components.RoundedPanel();
        roundedPanel4 = new wastemanagement.components.RoundedPanel();
        Greeting3 = new javax.swing.JLabel();
        HomeIcon2 = new javax.swing.JLabel();
        roundedPanel6 = new wastemanagement.components.RoundedPanel();
        roundedPanel5 = new wastemanagement.components.RoundedPanel();
        Greeting4 = new javax.swing.JLabel();
        HomeIcon3 = new javax.swing.JLabel();
        roundedPanel7 = new wastemanagement.components.RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Greeting2 = new javax.swing.JLabel();
        roundedPanel3 = new wastemanagement.components.RoundedPanel();
        jTextField1 = new javax.swing.JTextField();
        roundedPanel9 = new wastemanagement.components.RoundedPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel22 = new wastemanagement.components.RoundedPanel();
        Greeting9 = new javax.swing.JLabel();
        roundedPanel23 = new wastemanagement.components.RoundedPanel();
        roundedPanel25 = new wastemanagement.components.RoundedPanel();
        Greeting11 = new javax.swing.JLabel();
        roundedPanel14 = new wastemanagement.components.RoundedPanel();
        roundedPanel10 = new wastemanagement.components.RoundedPanel();
        Greeting7 = new javax.swing.JLabel();
        Greeting8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roundedPanel11 = new wastemanagement.components.RoundedPanel();
        Greeting5 = new javax.swing.JLabel();
        roundedPanel12 = new wastemanagement.components.RoundedPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        roundedPanel17 = new wastemanagement.components.RoundedPanel();
        jTextField6 = new javax.swing.JTextField();
        removeMat = new javax.swing.JLabel();
        roundedPanel18 = new wastemanagement.components.RoundedPanel();
        jTextField7 = new javax.swing.JTextField();
        Greeting6 = new javax.swing.JLabel();
        Greeting = new javax.swing.JLabel();
        addStepButton = new wastemanagement.components.RoundedPanel();
        Greeting14 = new javax.swing.JLabel();
        addStepButtonShadow = new wastemanagement.components.RoundedPanel();
        jPanel6 = new javax.swing.JPanel();
        Greeting15 = new javax.swing.JLabel();
        Greeting16 = new javax.swing.JLabel();
        roundedPanel20 = new wastemanagement.components.RoundedPanel();
        jTextField4 = new javax.swing.JTextField();
        roundedPanel13 = new wastemanagement.components.RoundedPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        removeStep1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1340, 800));
        setMinimumSize(new java.awt.Dimension(1355, 840));
        setPreferredSize(new java.awt.Dimension(1355, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1340, 800));

        BackgroundPane.setBackground(new java.awt.Color(85, 136, 59));
        BackgroundPane.setOpaque(true);

        ContentSection.setBackground(new java.awt.Color(230, 240, 220));
        ContentSection.setRoundTopLeft(60);
        ContentSection.setRoundTopRight(60);
        ContentSection.setLayout(null);

        roundedPanel4.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel4.setRoundBottomLeft(30);
        roundedPanel4.setRoundBottomRight(30);
        roundedPanel4.setRoundTopLeft(30);
        roundedPanel4.setRoundTopRight(30);
        roundedPanel4.setLayout(null);

        Greeting3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting3.setText("Save");
        Greeting3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel4.add(Greeting3);
        Greeting3.setBounds(40, 0, 70, 30);

        HomeIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go back.png"))); // NOI18N
        HomeIcon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel4.add(HomeIcon2);
        HomeIcon2.setBounds(10, 0, 20, 30);

        ContentSection.add(roundedPanel4);
        roundedPanel4.setBounds(990, 20, 130, 30);

        roundedPanel6.setBackground(new java.awt.Color(153, 153, 153));
        roundedPanel6.setRoundBottomLeft(30);
        roundedPanel6.setRoundBottomRight(30);
        roundedPanel6.setRoundTopLeft(30);
        roundedPanel6.setRoundTopRight(30);

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ContentSection.add(roundedPanel6);
        roundedPanel6.setBounds(990, 23, 130, 30);

        roundedPanel5.setRoundBottomLeft(30);
        roundedPanel5.setRoundBottomRight(30);
        roundedPanel5.setRoundTopLeft(30);
        roundedPanel5.setRoundTopRight(30);
        roundedPanel5.setLayout(null);

        Greeting4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting4.setText("Cancel");
        Greeting4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel5.add(Greeting4);
        Greeting4.setBounds(40, 0, 70, 30);

        HomeIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go back.png"))); // NOI18N
        HomeIcon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel5.add(HomeIcon3);
        HomeIcon3.setBounds(10, 0, 20, 30);

        ContentSection.add(roundedPanel5);
        roundedPanel5.setBounds(1150, 20, 130, 30);

        roundedPanel7.setBackground(new java.awt.Color(153, 153, 153));
        roundedPanel7.setRoundBottomLeft(30);
        roundedPanel7.setRoundBottomRight(30);
        roundedPanel7.setRoundTopLeft(30);
        roundedPanel7.setRoundTopRight(30);

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ContentSection.add(roundedPanel7);
        roundedPanel7.setBounds(1150, 23, 130, 30);

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(230, 240, 220));
        jPanel1.setLayout(null);

        Greeting2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        Greeting2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Greeting2.setText("Other Materials:");
        Greeting2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Greeting2);
        Greeting2.setBounds(0, 60, 590, 40);

        roundedPanel3.setBackground(new java.awt.Color(245, 245, 245));
        roundedPanel3.setRoundBottomLeft(40);
        roundedPanel3.setRoundBottomRight(40);
        roundedPanel3.setRoundTopLeft(40);
        roundedPanel3.setRoundTopRight(40);
        roundedPanel3.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(245, 245, 245));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        roundedPanel3.add(jTextField1);
        jTextField1.setBounds(20, 0, 400, 40);

        jPanel1.add(roundedPanel3);
        roundedPanel3.setBounds(150, 0, 440, 40);

        roundedPanel9.setBackground(new java.awt.Color(183, 222, 137));
        roundedPanel9.setRoundBottomLeft(50);
        roundedPanel9.setRoundBottomRight(50);
        roundedPanel9.setRoundTopLeft(50);
        roundedPanel9.setRoundTopRight(50);
        roundedPanel9.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.setLayout(null);
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 250);

        roundedPanel9.add(jPanel4);
        jPanel4.setBounds(20, 20, 550, 250);

        roundedPanel22.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel22.setRoundBottomLeft(30);
        roundedPanel22.setRoundBottomRight(30);
        roundedPanel22.setRoundTopLeft(30);
        roundedPanel22.setRoundTopRight(30);
        roundedPanel22.setLayout(null);

        Greeting9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting9.setText("Upload");
        Greeting9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel22.add(Greeting9);
        Greeting9.setBounds(30, 0, 70, 30);

        roundedPanel9.add(roundedPanel22);
        roundedPanel22.setBounds(120, 287, 130, 30);

        roundedPanel23.setBackground(new java.awt.Color(153, 153, 153));
        roundedPanel23.setRoundBottomLeft(30);
        roundedPanel23.setRoundBottomRight(30);
        roundedPanel23.setRoundTopLeft(30);
        roundedPanel23.setRoundTopRight(30);

        javax.swing.GroupLayout roundedPanel23Layout = new javax.swing.GroupLayout(roundedPanel23);
        roundedPanel23.setLayout(roundedPanel23Layout);
        roundedPanel23Layout.setHorizontalGroup(
            roundedPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        roundedPanel23Layout.setVerticalGroup(
            roundedPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        roundedPanel9.add(roundedPanel23);
        roundedPanel23.setBounds(120, 290, 130, 30);

        roundedPanel25.setRoundBottomLeft(30);
        roundedPanel25.setRoundBottomRight(30);
        roundedPanel25.setRoundTopLeft(30);
        roundedPanel25.setRoundTopRight(30);
        roundedPanel25.setLayout(null);

        Greeting11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting11.setText("Remove");
        Greeting11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedPanel25.add(Greeting11);
        Greeting11.setBounds(30, 0, 70, 30);

        roundedPanel9.add(roundedPanel25);
        roundedPanel25.setBounds(340, 287, 130, 30);

        roundedPanel14.setBackground(new java.awt.Color(153, 153, 153));
        roundedPanel14.setMinimumSize(new java.awt.Dimension(130, 30));
        roundedPanel14.setRoundBottomLeft(30);
        roundedPanel14.setRoundBottomRight(30);
        roundedPanel14.setRoundTopLeft(30);
        roundedPanel14.setRoundTopRight(30);

        javax.swing.GroupLayout roundedPanel14Layout = new javax.swing.GroupLayout(roundedPanel14);
        roundedPanel14.setLayout(roundedPanel14Layout);
        roundedPanel14Layout.setHorizontalGroup(
            roundedPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        roundedPanel14Layout.setVerticalGroup(
            roundedPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        roundedPanel9.add(roundedPanel14);
        roundedPanel14.setBounds(340, 290, 130, 30);

        jPanel1.add(roundedPanel9);
        roundedPanel9.setBounds(660, 20, 590, 330);

        roundedPanel10.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel10.setRoundBottomLeft(50);
        roundedPanel10.setRoundBottomRight(50);
        roundedPanel10.setRoundTopLeft(50);
        roundedPanel10.setRoundTopRight(50);
        roundedPanel10.setLayout(null);

        Greeting7.setFont(new java.awt.Font("Nirmala UI", 3, 14)); // NOI18N
        Greeting7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting7.setText("Q u a n t i t y");
        Greeting7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedPanel10.add(Greeting7);
        Greeting7.setBounds(30, 10, 130, 20);

        Greeting8.setFont(new java.awt.Font("Nirmala UI", 3, 14)); // NOI18N
        Greeting8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting8.setText("I t e m  N a m e");
        Greeting8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedPanel10.add(Greeting8);
        Greeting8.setBounds(170, 10, 330, 20);

        jPanel2.setBackground(new java.awt.Color(183, 222, 137));
        jPanel2.setLayout(null);

        roundedPanel11.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel11.setRoundBottomLeft(30);
        roundedPanel11.setRoundBottomRight(30);
        roundedPanel11.setRoundTopLeft(30);
        roundedPanel11.setRoundTopRight(30);
        roundedPanel11.setLayout(null);

        Greeting5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting5.setText("Add Item");
        Greeting5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Greeting5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewItem(evt);
            }
        });
        roundedPanel11.add(Greeting5);
        Greeting5.setBounds(30, 0, 70, 30);

        jPanel2.add(roundedPanel11);
        roundedPanel11.setBounds(210, 167, 130, 30);

        roundedPanel12.setBackground(new java.awt.Color(153, 153, 153));
        roundedPanel12.setRoundBottomLeft(30);
        roundedPanel12.setRoundBottomRight(30);
        roundedPanel12.setRoundTopLeft(30);
        roundedPanel12.setRoundTopRight(30);

        javax.swing.GroupLayout roundedPanel12Layout = new javax.swing.GroupLayout(roundedPanel12);
        roundedPanel12.setLayout(roundedPanel12Layout);
        roundedPanel12Layout.setHorizontalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        roundedPanel12Layout.setVerticalGroup(
            roundedPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(roundedPanel12);
        roundedPanel12.setBounds(210, 170, 130, 30);

        jScrollPane3.setBorder(null);

        jPanel5.setBackground(new java.awt.Color(183, 222, 137));
        jPanel5.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(183, 222, 137));
        jPanel3.setLayout(null);

        roundedPanel17.setBackground(new java.awt.Color(245, 245, 245));
        roundedPanel17.setRoundBottomLeft(40);
        roundedPanel17.setRoundBottomRight(40);
        roundedPanel17.setRoundTopLeft(40);
        roundedPanel17.setRoundTopRight(40);
        roundedPanel17.setLayout(null);

        jTextField6.setBackground(new java.awt.Color(245, 245, 245));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        roundedPanel17.add(jTextField6);
        jTextField6.setBounds(20, 0, 90, 40);

        jPanel3.add(roundedPanel17);
        roundedPanel17.setBounds(10, 10, 130, 40);

        removeMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-drop-left-line.png"))); // NOI18N
        removeMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteItem(evt);
            }
        });
        jPanel3.add(removeMat);
        removeMat.setBounds(490, 10, 40, 40);

        roundedPanel18.setBackground(new java.awt.Color(245, 245, 245));
        roundedPanel18.setRoundBottomLeft(40);
        roundedPanel18.setRoundBottomRight(40);
        roundedPanel18.setRoundTopLeft(40);
        roundedPanel18.setRoundTopRight(40);
        roundedPanel18.setLayout(null);

        jTextField7.setBackground(new java.awt.Color(245, 245, 245));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        roundedPanel18.add(jTextField7);
        jTextField7.setBounds(20, 0, 290, 40);

        jPanel3.add(roundedPanel18);
        roundedPanel18.setBounds(150, 10, 330, 40);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(0, 10, 550, 60);

        jScrollPane3.setViewportView(jPanel5);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 550, 160);

        roundedPanel10.add(jPanel2);
        jPanel2.setBounds(20, 30, 550, 210);

        jPanel1.add(roundedPanel10);
        roundedPanel10.setBounds(0, 100, 590, 250);

        Greeting6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        Greeting6.setForeground(new java.awt.Color(85, 136, 59));
        Greeting6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting6.setText("Item Name:");
        jPanel1.add(Greeting6);
        Greeting6.setBounds(0, 0, 150, 40);

        Greeting.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        Greeting.setForeground(new java.awt.Color(85, 136, 59));
        Greeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting.setText("Step-by-Step Tutorial");
        jPanel1.add(Greeting);
        Greeting.setBounds(0, 360, 1250, 50);

        addStepButton.setBackground(new java.awt.Color(193, 232, 153));
        addStepButton.setRoundBottomLeft(30);
        addStepButton.setRoundBottomRight(30);
        addStepButton.setRoundTopLeft(30);
        addStepButton.setRoundTopRight(30);
        addStepButton.setLayout(null);

        Greeting14.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Greeting14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Greeting14.setText("Add Step");
        Greeting14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Greeting14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewStep(evt);
            }
        });
        addStepButton.add(Greeting14);
        Greeting14.setBounds(30, 0, 70, 30);

        jPanel1.add(addStepButton);
        addStepButton.setBounds(550, 637, 130, 30);

        addStepButtonShadow.setBackground(new java.awt.Color(153, 153, 153));
        addStepButtonShadow.setRoundBottomLeft(30);
        addStepButtonShadow.setRoundBottomRight(30);
        addStepButtonShadow.setRoundTopLeft(30);
        addStepButtonShadow.setRoundTopRight(30);

        javax.swing.GroupLayout addStepButtonShadowLayout = new javax.swing.GroupLayout(addStepButtonShadow);
        addStepButtonShadow.setLayout(addStepButtonShadowLayout);
        addStepButtonShadowLayout.setHorizontalGroup(
            addStepButtonShadowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        addStepButtonShadowLayout.setVerticalGroup(
            addStepButtonShadowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(addStepButtonShadow);
        addStepButtonShadow.setBounds(550, 640, 130, 30);

        jPanel6.setBackground(new java.awt.Color(230, 240, 220));
        jPanel6.setLayout(null);

        Greeting15.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        Greeting15.setForeground(new java.awt.Color(85, 136, 59));
        Greeting15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Greeting15.setText("Step:");
        jPanel6.add(Greeting15);
        Greeting15.setBounds(6, 0, 87, 40);

        Greeting16.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        Greeting16.setForeground(new java.awt.Color(85, 136, 59));
        Greeting16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Greeting16.setText("Details:");
        jPanel6.add(Greeting16);
        Greeting16.setBounds(6, 50, 87, 40);

        roundedPanel20.setBackground(new java.awt.Color(245, 245, 245));
        roundedPanel20.setRoundBottomLeft(40);
        roundedPanel20.setRoundBottomRight(40);
        roundedPanel20.setRoundTopLeft(40);
        roundedPanel20.setRoundTopRight(40);
        roundedPanel20.setLayout(null);

        jTextField4.setBackground(new java.awt.Color(245, 245, 245));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setBorder(null);
        roundedPanel20.add(jTextField4);
        jTextField4.setBounds(20, 0, 600, 40);

        jPanel6.add(roundedPanel20);
        roundedPanel20.setBounds(99, 0, 640, 40);

        roundedPanel13.setBackground(new java.awt.Color(245, 245, 245));
        roundedPanel13.setRoundBottomLeft(40);
        roundedPanel13.setRoundBottomRight(40);
        roundedPanel13.setRoundTopLeft(40);
        roundedPanel13.setRoundTopRight(40);
        roundedPanel13.setLayout(null);

        jScrollPane5.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(245, 245, 245));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(null);
        jScrollPane5.setViewportView(jTextArea2);

        roundedPanel13.add(jScrollPane5);
        jScrollPane5.setBounds(10, 10, 1140, 140);

        jPanel6.add(roundedPanel13);
        roundedPanel13.setBounds(99, 50, 1161, 160);

        removeStep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-drop-left-line.png"))); // NOI18N
        removeStep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStep1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeStep(evt);
            }
        });
        jPanel6.add(removeStep1);
        removeStep1.setBounds(1129, 4, 40, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(-10, 410, 1260, 220);

        jScrollPane1.setViewportView(jPanel1);

        ContentSection.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 1280, 670);

        BackgroundPane.setLayer(ContentSection, javax.swing.JLayeredPane.POPUP_LAYER);
        BackgroundPane.add(ContentSection);
        ContentSection.setBounds(0, 62, 1340, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void AddNewItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewItem
        
        JPanel latestLine = itemPanelCollection.get(itemPanelCollection.size() - 1);
        JPanel newLine = cloneItemPanel(latestLine);
        
        jPanel5.add(newLine);
        
        if (newLine.getY() + newLine.getHeight() > jPanel5.getHeight())
        {
            int newHeight = newLine.getY() + newLine.getHeight();
            jPanel5.setPreferredSize(new Dimension(jPanel5.getPreferredSize().width, newHeight));
        }
        
        jPanel5.revalidate();
        jPanel5.repaint();
        
        itemPanelCollection.add(newLine);
    }//GEN-LAST:event_AddNewItem

    private void deleteItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteItem

        JLabel source = (JLabel) evt.getSource();

        JPanel currentPanel = (JPanel) source.getParent();
        JPanel parentPanel = (JPanel) currentPanel.getParent();

        if (itemPanelCollection.size() == 1)
        {
            return;
        }
        itemPanelCollection.remove(currentPanel);

        // Shift the remaining panels upwards
        for (JPanel line : itemPanelCollection) {
            if (line.getY() > currentPanel.getY()) {
                // Calculate the new Y position by subtracting the height of the currentPanel
                int newY = line.getY() - currentPanel.getHeight() + 10;
                line.setBounds(line.getX(), newY, line.getWidth(), line.getHeight());
            }
        }

        parentPanel.remove(currentPanel);

        // Dynamically adjust the parent panel's preferred size
        int newHeight = 0;
        for (JPanel line : itemPanelCollection) {
            newHeight = Math.max(newHeight, line.getY() + line.getHeight()); // Get the height based on the last panel
        }

        // Set the preferred size of the parent panel, this triggers re-layout within a JScrollPane
        parentPanel.setPreferredSize(new Dimension(parentPanel.getWidth(), newHeight));

        // Revalidate and repaint the parent panel to ensure the layout is updated
        parentPanel.revalidate();
        parentPanel.repaint();
    }//GEN-LAST:event_deleteItem

    private void addNewStep(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewStep
        JPanel latestStep = stepPanelCollection.get(stepPanelCollection.size() - 1);
        JPanel newStep = cloneStepPanel(latestStep);

        jPanel1.add(newStep);

        addStepButton.setBounds(addStepButton.getX(), (newStep.getY() + newStep.getHeight()), addStepButton.getWidth(), addStepButton.getHeight());
        addStepButtonShadow.setBounds(addStepButtonShadow.getX(), (newStep.getY() + newStep.getHeight() + 3), addStepButtonShadow.getWidth(), addStepButtonShadow.getHeight());

        if (addStepButtonShadow.getY() + addStepButtonShadow.getHeight() > jPanel1.getHeight())
        {
            int newHeight = addStepButtonShadow.getY() + addStepButtonShadow.getHeight() + 30;
            jPanel1.setPreferredSize(new Dimension(jPanel1.getPreferredSize().width, newHeight));
        }

        jPanel1.revalidate();
        jPanel1.repaint();

        stepPanelCollection.add(newStep);
    }//GEN-LAST:event_addNewStep

    private void removeStep(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeStep
        JLabel source = (JLabel) evt.getSource();

        JPanel currentPanel = (JPanel) source.getParent();
        JPanel parentPanel = (JPanel) currentPanel.getParent();

        if (stepPanelCollection.size() == 1)
        {
            return;
        }
        System.out.println(stepPanelCollection.size());
        stepPanelCollection.remove(currentPanel);

        // Shift the remaining panels upwards
        for (JPanel line : stepPanelCollection) {
            if (line.getY() > currentPanel.getY()) {
                // Calculate the new Y position by subtracting the height of the currentPanel
                int newY = line.getY() - (currentPanel.getHeight() + 30);
                line.setBounds(line.getX(), newY, line.getWidth(), line.getHeight());
            }
        }

        parentPanel.remove(currentPanel);
        System.out.println(stepPanelCollection.size());
        JPanel latestStep = stepPanelCollection.get(stepPanelCollection.size() - 1);
        addStepButton.setBounds(addStepButton.getX(), (latestStep.getY() + latestStep.getHeight()), addStepButton.getWidth(), addStepButton.getHeight());
        addStepButtonShadow.setBounds(addStepButtonShadow.getX(), (latestStep.getY() + latestStep.getHeight() + 3), addStepButtonShadow.getWidth(), addStepButtonShadow.getHeight());
        // Dynamically adjust the parent panel's preferred size
        int newHeight = addStepButtonShadow.getY() + addStepButtonShadow.getHeight() + 30;
        

        // Set the preferred size of the parent panel, this triggers re-layout within a JScrollPane
        parentPanel.setPreferredSize(new Dimension(parentPanel.getWidth(), newHeight));

        // Revalidate and repaint the parent panel to ensure the layout is updated
        parentPanel.revalidate();
        parentPanel.repaint();
    }//GEN-LAST:event_removeStep

    private JPanel cloneItemPanel(JPanel original) {
        JPanel copy = new JPanel();
        copy.setLayout(original.getLayout());
        copy.setBorder(original.getBorder());
        copy.setBounds(original.getX(), original.getY() + 50, original.getWidth(), original.getHeight());
        copy.setBackground(original.getBackground());

        
        
        for (Component comp : original.getComponents()) {
            if (comp instanceof JLabel) 
            {
                JLabel originalButton = (JLabel) comp;
                JLabel copyButton = new JLabel(originalButton.getText());
                copyButton.setIcon(originalButton.getIcon());
                copyButton.setCursor(originalButton.getCursor());
                copyButton.setBounds(originalButton.getX(), originalButton.getY(), originalButton.getWidth(), originalButton.getHeight());
                copyButton.addMouseListener(new java.awt.event.MouseAdapter()
                    {
                        public void mouseClicked(java.awt.event.MouseEvent evt)
                        {
                            deleteItem(evt);
                        }
                    }
                );
                copy.add(copyButton);
            }
            else if(comp instanceof RoundedPanel)
            {
                RoundedPanel originalPanel = (RoundedPanel) comp;
                RoundedPanel copyPanel = new RoundedPanel();
                copyPanel.setLayout(original.getLayout());
                copyPanel.setRoundTopLeft(originalPanel.getRoundTopLeft());
                copyPanel.setRoundTopRight(originalPanel.getRoundTopRight());
                copyPanel.setRoundBottomLeft(originalPanel.getRoundBottomLeft());
                copyPanel.setRoundBottomRight(originalPanel.getRoundBottomRight());
                copyPanel.setBackground(originalPanel.getBackground());
                

                for (Component innerComp : originalPanel.getComponents()) {
                    if (innerComp instanceof JTextField) {
                        JTextField originalField = (JTextField) innerComp;
                        JTextField copyField = new JTextField("", originalField.getColumns()); // Set default text
                        copyField.setFont(originalField.getFont());
                        copyField.setBackground(originalField.getBackground());
                        copyField.setForeground(originalField.getForeground());
                        copyField.setBounds(originalField.getX(), 0, originalPanel.getWidth() - 30, 40);
                        copyField.setBorder(originalField.getBorder());
                        copyField.setHorizontalAlignment(originalField.getHorizontalAlignment());
                        copyField.setCaretPosition(0);  // Set caret position to the beginning for default text
                        Dimension originalSize = originalField.getPreferredSize();
                        copyField.setPreferredSize(originalSize);
                        copyPanel.add(copyField);
                    }
                }

                copyPanel.setBounds(originalPanel.getX(), originalPanel.getY(), originalPanel.getWidth(), originalPanel.getHeight());
                copy.add(copyPanel);
            }

            
        }
        return copy;
    }    
    
    private JPanel cloneStepPanel(JPanel original) {
        JPanel copy = new JPanel();
        copy.setLayout(original.getLayout());
        copy.setBorder(original.getBorder());
        copy.setBounds(original.getX(), original.getY() + 250, original.getWidth(), original.getHeight());
        copy.setBackground(original.getBackground());

        for (Component comp : original.getComponents()) {
            if (comp instanceof JLabel) 
            {
                    
                
                JLabel labelsAndButton = (JLabel) comp;
                JLabel copylabelsAndButton = new JLabel(labelsAndButton.getText());
                if (labelsAndButton.getText().equals(""))
                {
                    copylabelsAndButton.setIcon(labelsAndButton.getIcon());
                }
                else
                {
                    copylabelsAndButton.setFont(labelsAndButton.getFont());
                    copylabelsAndButton.setForeground(labelsAndButton.getForeground());
                    
                }         
                copylabelsAndButton.setHorizontalAlignment(labelsAndButton.getHorizontalAlignment());
                copylabelsAndButton.setCursor(labelsAndButton.getCursor());
                copylabelsAndButton.setBounds(labelsAndButton.getX(), labelsAndButton.getY(), labelsAndButton.getWidth(), labelsAndButton.getHeight());
                copylabelsAndButton.addMouseListener(new java.awt.event.MouseAdapter()
                    {
                        public void mouseClicked(java.awt.event.MouseEvent evt)
                        {
                            removeStep(evt);
                        }
                    }
                );
                copy.add(copylabelsAndButton);
            }
            else if(comp instanceof RoundedPanel)
            {
                RoundedPanel originalPanel = (RoundedPanel) comp;
                RoundedPanel copyPanel = new RoundedPanel();
                copyPanel.setLayout(original.getLayout());
                copyPanel.setRoundTopLeft(originalPanel.getRoundTopLeft());
                copyPanel.setRoundTopRight(originalPanel.getRoundTopRight());
                copyPanel.setRoundBottomLeft(originalPanel.getRoundBottomLeft());
                copyPanel.setRoundBottomRight(originalPanel.getRoundBottomRight());
                copyPanel.setBackground(originalPanel.getBackground());

                for (Component innerComp : originalPanel.getComponents()) {
                    if (innerComp instanceof JTextField)
                    {
                        JTextField originalField = (JTextField) innerComp;
                        JTextField copyField = new JTextField("", originalField.getColumns()); // Set default text
                        copyField.setFont(originalField.getFont());
                        copyField.setBackground(originalField.getBackground());
                        copyField.setForeground(originalField.getForeground());
                        copyField.setBounds(originalField.getX(), 0, originalPanel.getWidth() - 30, 40);
                        copyField.setBorder(originalField.getBorder());
                        copyField.setHorizontalAlignment(originalField.getHorizontalAlignment());
                        copyField.setCaretPosition(0);  // Set caret position to the beginning for default text
                        Dimension originalSize = originalField.getPreferredSize();
                        copyField.setPreferredSize(originalSize);
                        copyPanel.add(copyField);
                    }
                    else if (innerComp instanceof JScrollPane) {
                        JScrollPane originalScrollPane = (JScrollPane) innerComp;
                        Component view = originalScrollPane.getViewport().getView();
                        

                        if (view instanceof JTextArea) {
                            JTextArea originalArea = (JTextArea) view;
                            JTextArea copyArea = new JTextArea(originalArea.getText(), originalArea.getRows(), originalArea.getColumns());
                            copyArea.setFont(originalArea.getFont());
                            copyArea.setBackground(originalArea.getBackground());
                            copyArea.setForeground(originalArea.getForeground());
                            copyArea.setBorder(originalArea.getBorder());
                            copyArea.setCaretPosition(0);
                            copyArea.setLineWrap(true);
                            copyArea.setWrapStyleWord(true);
                            copyArea.setPreferredSize(originalArea.getPreferredSize());

                            JScrollPane copyScrollPane = new JScrollPane(copyArea);
                            copyScrollPane.setBounds(originalScrollPane.getBounds());
                            copyScrollPane.setBorder(originalScrollPane.getBorder());
                            copyPanel.add(copyScrollPane);
                            System.out.println("Copied JTextArea inside JScrollPane");
                        }
                    }
                }

                copyPanel.setBounds(originalPanel.getX(), originalPanel.getY(), originalPanel.getWidth(), originalPanel.getHeight());
                copy.add(copyPanel);
            }

            
        }
        return copy;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BackgroundPane;
    private wastemanagement.components.RoundedPanel ContentSection;
    private javax.swing.JLabel Greeting;
    private javax.swing.JLabel Greeting11;
    private javax.swing.JLabel Greeting14;
    private javax.swing.JLabel Greeting15;
    private javax.swing.JLabel Greeting16;
    private javax.swing.JLabel Greeting2;
    private javax.swing.JLabel Greeting3;
    private javax.swing.JLabel Greeting4;
    private javax.swing.JLabel Greeting5;
    private javax.swing.JLabel Greeting6;
    private javax.swing.JLabel Greeting7;
    private javax.swing.JLabel Greeting8;
    private javax.swing.JLabel Greeting9;
    private javax.swing.JLabel HomeIcon2;
    private javax.swing.JLabel HomeIcon3;
    private wastemanagement.components.RoundedPanel addStepButton;
    private wastemanagement.components.RoundedPanel addStepButtonShadow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel removeMat;
    private javax.swing.JLabel removeStep1;
    private wastemanagement.components.RoundedPanel roundedPanel10;
    private wastemanagement.components.RoundedPanel roundedPanel11;
    private wastemanagement.components.RoundedPanel roundedPanel12;
    private wastemanagement.components.RoundedPanel roundedPanel13;
    private wastemanagement.components.RoundedPanel roundedPanel14;
    private wastemanagement.components.RoundedPanel roundedPanel17;
    private wastemanagement.components.RoundedPanel roundedPanel18;
    private wastemanagement.components.RoundedPanel roundedPanel20;
    private wastemanagement.components.RoundedPanel roundedPanel22;
    private wastemanagement.components.RoundedPanel roundedPanel23;
    private wastemanagement.components.RoundedPanel roundedPanel25;
    private wastemanagement.components.RoundedPanel roundedPanel3;
    private wastemanagement.components.RoundedPanel roundedPanel4;
    private wastemanagement.components.RoundedPanel roundedPanel5;
    private wastemanagement.components.RoundedPanel roundedPanel6;
    private wastemanagement.components.RoundedPanel roundedPanel7;
    private wastemanagement.components.RoundedPanel roundedPanel9;
    // End of variables declaration//GEN-END:variables
}
