/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

/**
 *
 * @author Dane Aldritch Datuin
 */
public class AdminHomepage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomepage
     */
    public AdminHomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPane = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel9 = new wastemanagement.components.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel1 = new wastemanagement.components.RoundedPanel();
        roundedPanel2 = new wastemanagement.components.RoundedPanel();
        roundedPanel3 = new wastemanagement.components.RoundedPanel();
        roundedPanel5 = new wastemanagement.components.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        scrollBarCustom1 = new com.mycompany.components.CustomScrollbar.ScrollBarCustom();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        roundedPanel6 = new wastemanagement.components.RoundedPanel();
        roundedPanel7 = new wastemanagement.components.RoundedPanel();
        jLabel14 = new javax.swing.JLabel();
        scrollBarCustom2 = new com.mycompany.components.CustomScrollbar.ScrollBarCustom();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        roundedPanel4 = new wastemanagement.components.RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        roundedPanel8 = new wastemanagement.components.RoundedPanel();
        jLabel22 = new javax.swing.JLabel();
        roundedPanel10 = new wastemanagement.components.RoundedPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        roundedPanel11 = new wastemanagement.components.RoundedPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WaIS: ADMIN HOMEPAGE");
        setResizable(false);

        BackgroundPane.setPreferredSize(new java.awt.Dimension(1355, 840));

        jPanel1.setBackground(new java.awt.Color(85, 136, 59));
        jPanel1.setPreferredSize(new java.awt.Dimension(1355, 840));

        roundedPanel9.setBackground(new java.awt.Color(230, 240, 220));
        roundedPanel9.setPreferredSize(new java.awt.Dimension(1260, 806));
        roundedPanel9.setRoundBottomLeft(100);
        roundedPanel9.setRoundBottomRight(100);
        roundedPanel9.setRoundTopLeft(100);
        roundedPanel9.setRoundTopRight(100);
        roundedPanel9.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 136, 59));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMIN");
        roundedPanel9.add(jLabel7);
        jLabel7.setBounds(380, 70, 500, 70);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADMIN");
        roundedPanel9.add(jLabel8);
        jLabel8.setBounds(380, 73, 500, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WaIS-Logo-03.png"))); // NOI18N
        roundedPanel9.add(jLabel1);
        jLabel1.setBounds(100, 30, 130, 160);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout-box-r-line.png"))); // NOI18N
        roundedPanel9.add(jLabel2);
        jLabel2.setBounds(1060, 80, 65, 70);

        roundedPanel1.setBackground(new java.awt.Color(247, 255, 238));
        roundedPanel1.setRoundBottomLeft(50);
        roundedPanel1.setRoundBottomRight(50);
        roundedPanel1.setRoundTopLeft(50);
        roundedPanel1.setRoundTopRight(50);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        roundedPanel9.add(roundedPanel1);
        roundedPanel1.setBounds(50, 30, 1170, 170);

        roundedPanel2.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel2.setRoundBottomLeft(50);
        roundedPanel2.setRoundBottomRight(50);
        roundedPanel2.setRoundTopLeft(50);
        roundedPanel2.setRoundTopRight(50);
        roundedPanel2.setLayout(null);

        roundedPanel3.setBackground(new java.awt.Color(246, 254, 238));
        roundedPanel3.setRoundBottomLeft(50);
        roundedPanel3.setRoundBottomRight(50);
        roundedPanel3.setRoundTopLeft(50);
        roundedPanel3.setRoundTopRight(50);
        roundedPanel3.setLayout(null);

        roundedPanel5.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel5.setRoundBottomLeft(50);
        roundedPanel5.setRoundBottomRight(50);
        roundedPanel5.setRoundTopLeft(50);
        roundedPanel5.setRoundTopRight(50);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Top Contributors:");

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        roundedPanel3.add(roundedPanel5);
        roundedPanel5.setBounds(33, 16, 355, 50);

        scrollBarCustom1.setBackground(new java.awt.Color(246, 254, 238));
        scrollBarCustom1.setForeground(new java.awt.Color(85, 136, 59));
        roundedPanel3.add(scrollBarCustom1);
        scrollBarCustom1.setBounds(385, 90, 18, 111);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contributions");
        roundedPanel3.add(jLabel4);
        jLabel4.setBounds(198, 72, 180, 25);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name");
        roundedPanel3.add(jLabel5);
        jLabel5.setBounds(33, 72, 170, 25);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel6.setText("1. [Name]");
        roundedPanel3.add(jLabel6);
        jLabel6.setBounds(33, 103, 176, 25);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel9.setText("2. [Name]");
        roundedPanel3.add(jLabel9);
        jLabel9.setBounds(33, 134, 176, 25);

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel10.setText("3. [Name]");
        roundedPanel3.add(jLabel10);
        jLabel10.setBounds(33, 165, 176, 25);

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("[Number]");
        roundedPanel3.add(jLabel11);
        jLabel11.setBounds(200, 103, 176, 25);

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("[Number]");
        roundedPanel3.add(jLabel12);
        jLabel12.setBounds(200, 134, 176, 25);

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("[Number]");
        roundedPanel3.add(jLabel13);
        jLabel13.setBounds(200, 165, 176, 25);

        roundedPanel2.add(roundedPanel3);
        roundedPanel3.setBounds(120, 50, 420, 220);

        roundedPanel6.setBackground(new java.awt.Color(246, 254, 238));
        roundedPanel6.setRoundBottomLeft(50);
        roundedPanel6.setRoundBottomRight(50);
        roundedPanel6.setRoundTopLeft(50);
        roundedPanel6.setRoundTopRight(50);
        roundedPanel6.setLayout(null);

        roundedPanel7.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel7.setRoundBottomLeft(50);
        roundedPanel7.setRoundBottomRight(50);
        roundedPanel7.setRoundTopLeft(50);
        roundedPanel7.setRoundTopRight(50);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Top Ideas:");

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        roundedPanel6.add(roundedPanel7);
        roundedPanel7.setBounds(33, 16, 355, 50);

        scrollBarCustom2.setBackground(new java.awt.Color(246, 254, 238));
        scrollBarCustom2.setForeground(new java.awt.Color(85, 136, 59));
        roundedPanel6.add(scrollBarCustom2);
        scrollBarCustom2.setBounds(385, 90, 18, 111);

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Idea No.");
        roundedPanel6.add(jLabel16);
        jLabel16.setBounds(33, 72, 170, 25);

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel17.setText("1. [Idea No.] [Idea Name]");
        roundedPanel6.add(jLabel17);
        jLabel17.setBounds(33, 103, 220, 25);

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel18.setText("2. [Idea No.] [Idea Name]");
        roundedPanel6.add(jLabel18);
        jLabel18.setBounds(33, 134, 220, 25);

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel19.setText("3. [Idea No.] [Idea Name]");
        roundedPanel6.add(jLabel19);
        jLabel19.setBounds(33, 165, 220, 25);

        roundedPanel2.add(roundedPanel6);
        roundedPanel6.setBounds(630, 50, 420, 220);

        roundedPanel4.setBackground(new java.awt.Color(246, 254, 238));
        roundedPanel4.setRoundBottomLeft(50);
        roundedPanel4.setRoundBottomRight(50);
        roundedPanel4.setRoundTopLeft(50);
        roundedPanel4.setRoundTopRight(50);
        roundedPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total Accounts:");
        roundedPanel4.add(jLabel15);
        jLabel15.setBounds(0, 20, 190, 40);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person.png"))); // NOI18N
        roundedPanel4.add(jLabel20);
        jLabel20.setBounds(90, 90, 70, 60);

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel21.setText("[Number]");
        roundedPanel4.add(jLabel21);
        jLabel21.setBounds(170, 100, 120, 40);

        roundedPanel8.setBackground(new java.awt.Color(85, 136, 59));
        roundedPanel8.setRoundBottomLeft(40);
        roundedPanel8.setRoundBottomRight(40);
        roundedPanel8.setRoundTopLeft(40);
        roundedPanel8.setRoundTopRight(40);

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Manage Users");

        javax.swing.GroupLayout roundedPanel8Layout = new javax.swing.GroupLayout(roundedPanel8);
        roundedPanel8.setLayout(roundedPanel8Layout);
        roundedPanel8Layout.setHorizontalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        roundedPanel8Layout.setVerticalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        roundedPanel4.add(roundedPanel8);
        roundedPanel8.setBounds(190, 20, 210, 40);

        roundedPanel2.add(roundedPanel4);
        roundedPanel4.setBounds(120, 290, 420, 180);

        roundedPanel10.setBackground(new java.awt.Color(246, 254, 238));
        roundedPanel10.setRoundBottomLeft(50);
        roundedPanel10.setRoundBottomRight(50);
        roundedPanel10.setRoundTopLeft(50);
        roundedPanel10.setRoundTopRight(50);
        roundedPanel10.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Total Ideas:");
        roundedPanel10.add(jLabel23);
        jLabel23.setBounds(0, 20, 190, 40);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightbulb-fill.png"))); // NOI18N
        roundedPanel10.add(jLabel24);
        jLabel24.setBounds(90, 90, 70, 60);

        jLabel25.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel25.setText("[Number]");
        roundedPanel10.add(jLabel25);
        jLabel25.setBounds(170, 100, 120, 40);

        roundedPanel11.setBackground(new java.awt.Color(85, 136, 59));
        roundedPanel11.setRoundBottomLeft(40);
        roundedPanel11.setRoundBottomRight(40);
        roundedPanel11.setRoundTopLeft(40);
        roundedPanel11.setRoundTopRight(40);

        jLabel26.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Manage Ideas");

        javax.swing.GroupLayout roundedPanel11Layout = new javax.swing.GroupLayout(roundedPanel11);
        roundedPanel11.setLayout(roundedPanel11Layout);
        roundedPanel11Layout.setHorizontalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        roundedPanel11Layout.setVerticalGroup(
            roundedPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        roundedPanel10.add(roundedPanel11);
        roundedPanel11.setBounds(190, 20, 210, 40);

        roundedPanel2.add(roundedPanel10);
        roundedPanel10.setBounds(630, 290, 420, 180);

        roundedPanel9.add(roundedPanel2);
        roundedPanel2.setBounds(50, 220, 1170, 490);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(roundedPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(roundedPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        BackgroundPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BackgroundPaneLayout = new javax.swing.GroupLayout(BackgroundPane);
        BackgroundPane.setLayout(BackgroundPaneLayout);
        BackgroundPaneLayout.setHorizontalGroup(
            BackgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundPaneLayout.setVerticalGroup(
            BackgroundPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BackgroundPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel10;
    private wastemanagement.components.RoundedPanel roundedPanel11;
    private wastemanagement.components.RoundedPanel roundedPanel2;
    private wastemanagement.components.RoundedPanel roundedPanel3;
    private wastemanagement.components.RoundedPanel roundedPanel4;
    private wastemanagement.components.RoundedPanel roundedPanel5;
    private wastemanagement.components.RoundedPanel roundedPanel6;
    private wastemanagement.components.RoundedPanel roundedPanel7;
    private wastemanagement.components.RoundedPanel roundedPanel8;
    private wastemanagement.components.RoundedPanel roundedPanel9;
    private com.mycompany.components.CustomScrollbar.ScrollBarCustom scrollBarCustom1;
    private com.mycompany.components.CustomScrollbar.ScrollBarCustom scrollBarCustom2;
    // End of variables declaration//GEN-END:variables
}
