/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

/**
 *
 * @author Dane Aldritch Datuin
 */
public class GeneralInformationPage extends javax.swing.JFrame {

    /**
     * Creates new form GeneralInformationPage
     */
    public GeneralInformationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPane = new javax.swing.JLayeredPane();
        ContentSection = new wastemanagement.components.RoundedPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        AccountTabShape = new wastemanagement.components.RoundedPanel();
        AccountTab = new javax.swing.JLabel();
        AccountLabel = new javax.swing.JLabel();
        AccountIcon = new javax.swing.JLabel();
        HomeTabShape = new wastemanagement.components.RoundedPanel();
        HomeLabel = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();
        HomeTab = new javax.swing.JLabel();
        InfoTabShape = new wastemanagement.components.RoundedPanel();
        InfoLabel = new javax.swing.JLabel();
        InfoIcon = new javax.swing.JLabel();
        MapTabShape = new wastemanagement.components.RoundedPanel();
        MapLabel = new javax.swing.JLabel();
        MapIcon = new javax.swing.JLabel();
        MapTab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1024));

        BackgroundPane.setBackground(new java.awt.Color(85, 136, 59));
        BackgroundPane.setOpaque(true);

        ContentSection.setBackground(new java.awt.Color(230, 240, 220));
        ContentSection.setRoundTopLeft(60);
        ContentSection.setRoundTopRight(60);
        ContentSection.setLayout(null);
        ContentSection.add(jScrollBar1);
        jScrollBar1.setBounds(1000, 20, 20, 550);

        BackgroundPane.setLayer(ContentSection, javax.swing.JLayeredPane.POPUP_LAYER);
        BackgroundPane.add(ContentSection);
        ContentSection.setBounds(0, 112, 1040, 590);

        AccountTabShape.setBackground(new java.awt.Color(193, 232, 153));
        AccountTabShape.setRoundTopLeft(60);
        AccountTabShape.setRoundTopRight(60);
        AccountTabShape.setLayout(null);

        AccountTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountTabShape.add(AccountTab);
        AccountTab.setBounds(0, 0, 200, 60);

        AccountLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountLabel.setText("Account");
        AccountTabShape.add(AccountLabel);
        AccountLabel.setBounds(70, 10, 110, 40);

        AccountIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\person.png")); // NOI18N
        AccountTabShape.add(AccountIcon);
        AccountIcon.setBounds(20, 10, 40, 40);

        BackgroundPane.setLayer(AccountTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(AccountTabShape);
        AccountTabShape.setBounds(780, 50, 200, 100);

        HomeTabShape.setBackground(new java.awt.Color(193, 232, 153));
        HomeTabShape.setRoundTopLeft(60);
        HomeTabShape.setRoundTopRight(60);
        HomeTabShape.setLayout(null);

        HomeLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeLabel.setText("Home");
        HomeTabShape.add(HomeLabel);
        HomeLabel.setBounds(90, 10, 80, 40);

        HomeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\Home.png")); // NOI18N
        HomeTabShape.add(HomeIcon);
        HomeIcon.setBounds(30, 10, 40, 40);

        HomeTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeTabShape.add(HomeTab);
        HomeTab.setBounds(0, 0, 200, 60);

        BackgroundPane.setLayer(HomeTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(HomeTabShape);
        HomeTabShape.setBounds(60, 50, 200, 90);

        InfoTabShape.setBackground(new java.awt.Color(230, 240, 220));
        InfoTabShape.setRoundTopLeft(60);
        InfoTabShape.setRoundTopRight(60);
        InfoTabShape.setLayout(null);

        InfoLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        InfoLabel.setText("Info");
        InfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoLabel);
        InfoLabel.setBounds(100, 20, 62, 40);

        InfoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\Info.png")); // NOI18N
        InfoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoIcon);
        InfoIcon.setBounds(40, 20, 40, 40);

        BackgroundPane.setLayer(InfoTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(InfoTabShape);
        InfoTabShape.setBounds(300, 30, 200, 100);

        MapTabShape.setBackground(new java.awt.Color(193, 232, 153));
        MapTabShape.setRoundTopLeft(60);
        MapTabShape.setRoundTopRight(60);
        MapTabShape.setLayout(null);

        MapLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        MapLabel.setText("Map");
        MapTabShape.add(MapLabel);
        MapLabel.setBounds(100, 10, 60, 40);

        MapIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\location.png")); // NOI18N
        MapIcon.setText("jLabel2");
        MapTabShape.add(MapIcon);
        MapIcon.setBounds(40, 10, 40, 40);

        MapTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        MapTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MapTabShape.add(MapTab);
        MapTab.setBounds(0, 0, 200, 60);

        BackgroundPane.setLayer(MapTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(MapTabShape);
        MapTabShape.setBounds(540, 50, 200, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralInformationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountIcon;
    private javax.swing.JLabel AccountLabel;
    private javax.swing.JLabel AccountTab;
    private wastemanagement.components.RoundedPanel AccountTabShape;
    private javax.swing.JLayeredPane BackgroundPane;
    private wastemanagement.components.RoundedPanel ContentSection;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel HomeTab;
    private wastemanagement.components.RoundedPanel HomeTabShape;
    private javax.swing.JLabel InfoIcon;
    private javax.swing.JLabel InfoLabel;
    private wastemanagement.components.RoundedPanel InfoTabShape;
    private javax.swing.JLabel MapIcon;
    private javax.swing.JLabel MapLabel;
    private javax.swing.JLabel MapTab;
    private wastemanagement.components.RoundedPanel MapTabShape;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
