/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

import com.mycompany.modules.UserAuthenticator;
import com.mycompany.modules.tables.Accounts;
import java.util.List;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Dane Aldritch Datuin
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        addMouseListenerToLoginBtn();
        addMouseListenerToSignUpBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new wastemanagement.components.RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        roundedPanel2 = new wastemanagement.components.RoundedPanel();
        LoginBtn = new javax.swing.JLabel();
        roundedPanel5 = new wastemanagement.components.RoundedPanel();
        SignUpBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel3 = new wastemanagement.components.RoundedPanel();
        EmailAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel4 = new wastemanagement.components.RoundedPanel();
        Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WaIS: LOGIN");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1355, 840));
        setMinimumSize(new java.awt.Dimension(1355, 840));
        setPreferredSize(new java.awt.Dimension(1355, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1355, 840));

        jPanel1.setBackground(new java.awt.Color(85, 136, 59));
        jPanel1.setLayout(null);

        roundedPanel1.setBackground(new java.awt.Color(230, 240, 220));
        roundedPanel1.setRoundBottomLeft(70);
        roundedPanel1.setRoundBottomRight(70);
        roundedPanel1.setRoundTopLeft(70);
        roundedPanel1.setRoundTopRight(70);
        roundedPanel1.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundedPanel1.add(jLabel4);
        jLabel4.setBounds(660, 20, 130, 140);

        roundedPanel2.setBackground(new java.awt.Color(193, 232, 153));
        roundedPanel2.setRoundBottomLeft(50);
        roundedPanel2.setRoundBottomRight(50);
        roundedPanel2.setRoundTopLeft(50);
        roundedPanel2.setRoundTopRight(50);

        LoginBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        LoginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginBtn.setText("Log In");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        roundedPanel1.add(roundedPanel2);
        roundedPanel2.setBounds(480, 460, 230, 55);

        roundedPanel5.setBackground(new java.awt.Color(164, 185, 143));
        roundedPanel5.setRoundBottomLeft(50);
        roundedPanel5.setRoundBottomRight(50);
        roundedPanel5.setRoundTopLeft(50);
        roundedPanel5.setRoundTopRight(50);

        SignUpBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpBtn.setText("Sign Up");
        SignUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SignUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SignUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        roundedPanel1.add(roundedPanel5);
        roundedPanel5.setBounds(110, 460, 230, 55);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("L O G I N");
        roundedPanel1.add(jLabel1);
        jLabel1.setBounds(310, 90, 220, 64);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setText("Email Address:");
        roundedPanel1.add(jLabel3);
        jLabel3.setBounds(100, 170, 165, 32);

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel3.setRoundBottomLeft(50);
        roundedPanel3.setRoundBottomRight(50);
        roundedPanel3.setRoundTopLeft(50);
        roundedPanel3.setRoundTopRight(50);

        EmailAddress.setFont(new java.awt.Font("Nirmala UI", 2, 24)); // NOI18N
        EmailAddress.setForeground(new java.awt.Color(128, 128, 128));
        EmailAddress.setText("Enter email");
        EmailAddress.setBorder(null);
        EmailAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        EmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailAddressFocusGained(evt);
            }
        });
        EmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(EmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roundedPanel1.add(roundedPanel3);
        roundedPanel3.setBounds(50, 220, 720, 55);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setText("Password:");
        roundedPanel1.add(jLabel2);
        jLabel2.setBounds(100, 300, 113, 32);

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel4.setRoundBottomLeft(50);
        roundedPanel4.setRoundBottomRight(50);
        roundedPanel4.setRoundTopLeft(50);
        roundedPanel4.setRoundTopRight(50);

        Password.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        Password.setBorder(null);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roundedPanel1.add(roundedPanel4);
        roundedPanel4.setBounds(50, 350, 720, 55);

        jPanel1.add(roundedPanel1);
        roundedPanel1.setBounds(260, 80, 820, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void EmailAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddressFocusGained
        if (EmailAddress.getText().equals("Enter email")) { 
            EmailAddress.setText("");
            EmailAddress.setFont(new Font("Nirmala UI", Font.PLAIN, 24));
            EmailAddress.setForeground(new Color(0, 0, 0)); 
        }
    }//GEN-LAST:event_EmailAddressFocusGained

    private void addMouseListenerToSignUpBtn() {
        SignUpBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                SignupPage signupPage = new SignupPage();
                signupPage.setVisible(true);
                dispose();
            }
        });
    }
    
    private void addMouseListenerToLoginBtn() {
        LoginBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String email = EmailAddress.getText();
                String password = new String(Password.getPassword());

                StringBuilder missingFields = new StringBuilder();
                if (email.isEmpty() || email.equals("Enter email")) 
                {
                    missingFields.append("Email Address\n");
                }
                if (password.isEmpty()) {
                    missingFields.append("Password\n");
                }
                if (missingFields.length() > 0) {
                    JOptionPane.showMessageDialog(null, "Please fill in the following fields:\n" + missingFields.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if(UserAuthenticator.authenticateLogin(email, password))
                {
                    JOptionPane.showMessageDialog(null, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    Accounts loggedAccount = UserAuthenticator.getAccount(email, password).get(0);
                    HomePage homePage = new HomePage(loggedAccount);
                    homePage.setLocationRelativeTo(null);
                    homePage.setVisible(true);
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid email or password", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailAddress;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel2;
    private wastemanagement.components.RoundedPanel roundedPanel3;
    private wastemanagement.components.RoundedPanel roundedPanel4;
    private wastemanagement.components.RoundedPanel roundedPanel5;
    // End of variables declaration//GEN-END:variables
}