/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

/**
 *
 * @author Dane Aldritch Datuin
 */
public class MapPage extends javax.swing.JFrame {

    /**
     * Creates new form MapPage
     */
    public MapPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPane = new javax.swing.JLayeredPane();
        ContentSection = new wastemanagement.components.RoundedPanel();
        roundedPanel1 = new wastemanagement.components.RoundedPanel();
        SearchBarShape = new wastemanagement.components.RoundedPanel();
        SearchBar = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JLabel();
        EnterIcon = new javax.swing.JLabel();
        EnterIcon1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        roundedPanel2 = new wastemanagement.components.RoundedPanel();
        SearchIcon1 = new javax.swing.JLabel();
        AccountTabShape = new wastemanagement.components.RoundedPanel();
        AccountTab = new javax.swing.JLabel();
        AccountLabel = new javax.swing.JLabel();
        AccountIcon = new javax.swing.JLabel();
        HomeTabShape = new wastemanagement.components.RoundedPanel();
        HomeLabel = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();
        HomeTab = new javax.swing.JLabel();
        InfoTabShape = new wastemanagement.components.RoundedPanel();
        InfoTab = new javax.swing.JLabel();
        InfoLabel = new javax.swing.JLabel();
        InfoIcon = new javax.swing.JLabel();
        MapTabShape = new wastemanagement.components.RoundedPanel();
        MapLabel = new javax.swing.JLabel();
        MapIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 1024));

        BackgroundPane.setBackground(new java.awt.Color(85, 136, 59));
        BackgroundPane.setOpaque(true);

        ContentSection.setBackground(new java.awt.Color(200, 210, 190));
        ContentSection.setRoundTopLeft(60);
        ContentSection.setRoundTopRight(60);
        ContentSection.setLayout(null);

        roundedPanel1.setBackground(new java.awt.Color(230, 240, 220));
        roundedPanel1.setRoundTopLeft(60);
        roundedPanel1.setRoundTopRight(60);
        roundedPanel1.setLayout(null);

        SearchBarShape.setBackground(new java.awt.Color(217, 217, 217));
        SearchBarShape.setRoundBottomLeft(50);
        SearchBarShape.setRoundBottomRight(50);
        SearchBarShape.setRoundTopLeft(50);
        SearchBarShape.setRoundTopRight(50);
        SearchBarShape.setLayout(null);

        SearchBar.setBackground(new java.awt.Color(217, 217, 217));
        SearchBar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(128, 128, 128));
        SearchBar.setText("Search a location");
        SearchBar.setBorder(null);
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBarShape.add(SearchBar);
        SearchBar.setBounds(40, 0, 390, 40);

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-Small.png"))); // NOI18N
        SearchBarShape.add(SearchIcon);
        SearchIcon.setBounds(10, 0, 20, 40);

        EnterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Right Arrow-Small.png"))); // NOI18N
        EnterIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBarShape.add(EnterIcon);
        EnterIcon.setBounds(580, 0, 20, 40);

        EnterIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Right Arrow-Small.png"))); // NOI18N
        EnterIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBarShape.add(EnterIcon1);
        EnterIcon1.setBounds(430, 0, 20, 40);

        roundedPanel1.add(SearchBarShape);
        SearchBarShape.setBounds(10, 30, 470, 40);

        jPanel1.setBackground(new java.awt.Color(230, 240, 220));
        jPanel1.setLayout(null);
        jPanel1.add(jScrollBar1);
        jScrollBar1.setBounds(475, 15, 10, 479);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 0, 440, 500);

        roundedPanel1.add(jPanel1);
        jPanel1.setBounds(0, 80, 500, 510);

        ContentSection.add(roundedPanel1);
        roundedPanel1.setBounds(0, 0, 500, 590);

        roundedPanel2.setBackground(new java.awt.Color(230, 240, 220));
        roundedPanel2.setRoundBottomRight(30);
        roundedPanel2.setRoundTopRight(30);
        roundedPanel2.setLayout(null);

        SearchIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-drop-left-line.png"))); // NOI18N
        roundedPanel2.add(SearchIcon1);
        SearchIcon1.setBounds(10, 30, 50, 40);

        ContentSection.add(roundedPanel2);
        roundedPanel2.setBounds(490, 250, 60, 100);

        BackgroundPane.setLayer(ContentSection, javax.swing.JLayeredPane.POPUP_LAYER);
        BackgroundPane.add(ContentSection);
        ContentSection.setBounds(0, 112, 1040, 590);

        AccountTabShape.setBackground(new java.awt.Color(193, 232, 153));
        AccountTabShape.setRoundTopLeft(60);
        AccountTabShape.setRoundTopRight(60);
        AccountTabShape.setLayout(null);

        AccountTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountTabShape.add(AccountTab);
        AccountTab.setBounds(0, 0, 200, 60);

        AccountLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        AccountLabel.setText("Account");
        AccountTabShape.add(AccountLabel);
        AccountLabel.setBounds(70, 10, 110, 40);

        AccountIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\person.png")); // NOI18N
        AccountTabShape.add(AccountIcon);
        AccountIcon.setBounds(20, 10, 40, 40);

        BackgroundPane.setLayer(AccountTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(AccountTabShape);
        AccountTabShape.setBounds(780, 50, 200, 100);

        HomeTabShape.setBackground(new java.awt.Color(193, 232, 153));
        HomeTabShape.setRoundTopLeft(60);
        HomeTabShape.setRoundTopRight(60);
        HomeTabShape.setLayout(null);

        HomeLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeLabel.setText("Home");
        HomeTabShape.add(HomeLabel);
        HomeLabel.setBounds(90, 10, 80, 40);

        HomeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\Home.png")); // NOI18N
        HomeTabShape.add(HomeIcon);
        HomeIcon.setBounds(30, 10, 40, 40);

        HomeTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        HomeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeTabShape.add(HomeTab);
        HomeTab.setBounds(0, 0, 200, 60);

        BackgroundPane.setLayer(HomeTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(HomeTabShape);
        HomeTabShape.setBounds(60, 50, 200, 90);

        InfoTabShape.setBackground(new java.awt.Color(193, 232, 153));
        InfoTabShape.setRoundTopLeft(60);
        InfoTabShape.setRoundTopRight(60);
        InfoTabShape.setLayout(null);

        InfoTab.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        InfoTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoTab);
        InfoTab.setBounds(0, 0, 200, 60);

        InfoLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        InfoLabel.setText("Info");
        InfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoLabel);
        InfoLabel.setBounds(100, 10, 62, 40);

        InfoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\Info.png")); // NOI18N
        InfoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoTabShape.add(InfoIcon);
        InfoIcon.setBounds(40, 10, 40, 40);

        BackgroundPane.setLayer(InfoTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(InfoTabShape);
        InfoTabShape.setBounds(300, 50, 200, 100);

        MapTabShape.setBackground(new java.awt.Color(230, 240, 220));
        MapTabShape.setRoundTopLeft(60);
        MapTabShape.setRoundTopRight(60);
        MapTabShape.setLayout(null);

        MapLabel.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        MapLabel.setText("Map");
        MapTabShape.add(MapLabel);
        MapLabel.setBounds(100, 20, 60, 40);

        MapIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dane Aldritch Datuin\\Documents\\NetBeansProjects\\WaIS\\src\\main\\resources\\location.png")); // NOI18N
        MapIcon.setText("jLabel2");
        MapTabShape.add(MapIcon);
        MapIcon.setBounds(40, 20, 40, 40);

        BackgroundPane.setLayer(MapTabShape, javax.swing.JLayeredPane.PALETTE_LAYER);
        BackgroundPane.add(MapTabShape);
        MapTabShape.setBounds(540, 30, 200, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountIcon;
    private javax.swing.JLabel AccountLabel;
    private javax.swing.JLabel AccountTab;
    private wastemanagement.components.RoundedPanel AccountTabShape;
    private javax.swing.JLayeredPane BackgroundPane;
    private wastemanagement.components.RoundedPanel ContentSection;
    private javax.swing.JLabel EnterIcon;
    private javax.swing.JLabel EnterIcon1;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel HomeTab;
    private wastemanagement.components.RoundedPanel HomeTabShape;
    private javax.swing.JLabel InfoIcon;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel InfoTab;
    private wastemanagement.components.RoundedPanel InfoTabShape;
    private javax.swing.JLabel MapIcon;
    private javax.swing.JLabel MapLabel;
    private wastemanagement.components.RoundedPanel MapTabShape;
    private javax.swing.JTextField SearchBar;
    private wastemanagement.components.RoundedPanel SearchBarShape;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JLabel SearchIcon1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private wastemanagement.components.RoundedPanel roundedPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
