/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userinterface;

import com.mycompany.modules.UserAuthenticator;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Dane Aldritch Datuin
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public SignupPage() {
        initComponents();
        addMouseListenerToSignUpBtn();
        addMouseListenerToGoBackBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new wastemanagement.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel5 = new wastemanagement.components.RoundedPanel();
        SignUpBtn = new javax.swing.JLabel();
        roundedPanel8 = new wastemanagement.components.RoundedPanel();
        GoBackBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel3 = new wastemanagement.components.RoundedPanel();
        FirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roundedPanel6 = new wastemanagement.components.RoundedPanel();
        LastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        roundedPanel7 = new wastemanagement.components.RoundedPanel();
        EmailAdd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        roundedPanel9 = new wastemanagement.components.RoundedPanel();
        PhoneNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        roundedPanel4 = new wastemanagement.components.RoundedPanel();
        Password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        roundedPanel10 = new wastemanagement.components.RoundedPanel();
        ConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WaIS: SIGNUP");
        setMaximumSize(new java.awt.Dimension(1355, 840));
        setMinimumSize(new java.awt.Dimension(1355, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1355, 840));

        jPanel1.setBackground(new java.awt.Color(85, 136, 59));
        jPanel1.setLayout(null);

        roundedPanel1.setBackground(new java.awt.Color(230, 240, 220));
        roundedPanel1.setRoundBottomLeft(70);
        roundedPanel1.setRoundBottomRight(70);
        roundedPanel1.setRoundTopLeft(70);
        roundedPanel1.setRoundTopRight(70);
        roundedPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("S I G N U P");
        roundedPanel1.add(jLabel1);
        jLabel1.setBounds(280, 10, 250, 64);

        roundedPanel5.setBackground(new java.awt.Color(164, 185, 143));
        roundedPanel5.setRoundBottomLeft(50);
        roundedPanel5.setRoundBottomRight(50);
        roundedPanel5.setRoundTopLeft(50);
        roundedPanel5.setRoundTopRight(50);

        SignUpBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpBtn.setText("Sign Up");
        SignUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel5);
        roundedPanel5.setBounds(460, 620, 230, 55);

        roundedPanel8.setBackground(new java.awt.Color(202, 232, 151));
        roundedPanel8.setRoundBottomLeft(50);
        roundedPanel8.setRoundBottomRight(50);
        roundedPanel8.setRoundTopLeft(50);
        roundedPanel8.setRoundTopRight(50);

        GoBackBtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        GoBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        GoBackBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GoBackBtn.setText("Go Back");
        GoBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel8Layout = new javax.swing.GroupLayout(roundedPanel8);
        roundedPanel8.setLayout(roundedPanel8Layout);
        roundedPanel8Layout.setHorizontalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GoBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        roundedPanel8Layout.setVerticalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GoBackBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel8);
        roundedPanel8.setBounds(110, 620, 230, 55);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setText("First Name");
        roundedPanel1.add(jLabel3);
        jLabel3.setBounds(80, 90, 123, 32);

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel3.setRoundBottomLeft(50);
        roundedPanel3.setRoundBottomRight(50);
        roundedPanel3.setRoundTopLeft(50);
        roundedPanel3.setRoundTopRight(50);

        FirstName.setFont(new java.awt.Font("Nirmala UI", 2, 24)); // NOI18N
        FirstName.setForeground(new java.awt.Color(144, 144, 144));
        FirstName.setText("Enter First Name");
        FirstName.setBorder(null);
        FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstNameFocusLost(evt);
            }
        });
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel3);
        roundedPanel3.setBounds(30, 130, 420, 55);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel6.setText("Last Name");
        roundedPanel1.add(jLabel6);
        jLabel6.setBounds(510, 90, 119, 32);

        roundedPanel6.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel6.setRoundBottomLeft(50);
        roundedPanel6.setRoundBottomRight(50);
        roundedPanel6.setRoundTopLeft(50);
        roundedPanel6.setRoundTopRight(50);

        LastName.setFont(new java.awt.Font("Nirmala UI", 2, 24)); // NOI18N
        LastName.setForeground(new java.awt.Color(144, 144, 144));
        LastName.setText("Enter Last Name");
        LastName.setBorder(null);
        LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel6);
        roundedPanel6.setBounds(460, 130, 330, 55);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel7.setText("E-Mail Address");
        roundedPanel1.add(jLabel7);
        jLabel7.setBounds(80, 190, 180, 32);

        roundedPanel7.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel7.setRoundBottomLeft(50);
        roundedPanel7.setRoundBottomRight(50);
        roundedPanel7.setRoundTopLeft(50);
        roundedPanel7.setRoundTopRight(50);

        EmailAdd.setFont(new java.awt.Font("Nirmala UI", 2, 24)); // NOI18N
        EmailAdd.setForeground(new java.awt.Color(144, 144, 144));
        EmailAdd.setText("Enter E-mail Address");
        EmailAdd.setBorder(null);
        EmailAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailAddFocusLost(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(EmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel7);
        roundedPanel7.setBounds(30, 230, 760, 55);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel8.setText("Phone Number");
        roundedPanel1.add(jLabel8);
        jLabel8.setBounds(80, 290, 180, 32);

        roundedPanel9.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel9.setRoundBottomLeft(50);
        roundedPanel9.setRoundBottomRight(50);
        roundedPanel9.setRoundTopLeft(50);
        roundedPanel9.setRoundTopRight(50);

        PhoneNum.setFont(new java.awt.Font("Nirmala UI", 2, 24)); // NOI18N
        PhoneNum.setForeground(new java.awt.Color(144, 144, 144));
        PhoneNum.setText("Enter Phone Number");
        PhoneNum.setBorder(null);
        PhoneNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNumFocusLost(evt);
            }
        });
        PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel9Layout = new javax.swing.GroupLayout(roundedPanel9);
        roundedPanel9.setLayout(roundedPanel9Layout);
        roundedPanel9Layout.setHorizontalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        roundedPanel9Layout.setVerticalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel9);
        roundedPanel9.setBounds(30, 330, 760, 55);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel9.setText("Password");
        roundedPanel1.add(jLabel9);
        jLabel9.setBounds(80, 390, 109, 32);

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel4.setRoundBottomLeft(50);
        roundedPanel4.setRoundBottomRight(50);
        roundedPanel4.setRoundTopLeft(50);
        roundedPanel4.setRoundTopRight(50);

        Password.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        Password.setBorder(null);

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel4);
        roundedPanel4.setBounds(30, 430, 760, 55);

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel10.setText("Confirm Password");
        roundedPanel1.add(jLabel10);
        jLabel10.setBounds(80, 490, 220, 32);

        roundedPanel10.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel10.setRoundBottomLeft(50);
        roundedPanel10.setRoundBottomRight(50);
        roundedPanel10.setRoundTopLeft(50);
        roundedPanel10.setRoundTopRight(50);

        ConfirmPassword.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        ConfirmPassword.setBorder(null);
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel10Layout = new javax.swing.GroupLayout(roundedPanel10);
        roundedPanel10.setLayout(roundedPanel10Layout);
        roundedPanel10Layout.setHorizontalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel10Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        roundedPanel10Layout.setVerticalGroup(
            roundedPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        roundedPanel1.add(roundedPanel10);
        roundedPanel10.setBounds(30, 530, 760, 55);

        jPanel1.add(roundedPanel1);
        roundedPanel1.setBounds(260, 40, 820, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusGained
        if (FirstName.getText().equals("Enter First Name")) { 
            FirstName.setText("");
            FirstName.setFont(new Font("Nirmala UI", Font.PLAIN, 24));
            FirstName.setForeground(new Color(0, 0, 0)); 
        }
    }//GEN-LAST:event_FirstNameFocusGained

    private void FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusLost
        if (FirstName.getText().equals("")) { 
            FirstName.setText("Enter First Name");
            FirstName.setFont(new Font("Nirmala UI", Font.ITALIC, 24));
            FirstName.setForeground(new Color(144, 144, 144)); 
        }        
    }//GEN-LAST:event_FirstNameFocusLost

    private void LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusGained
        if (LastName.getText().equals("Enter Last Name")) { 
            LastName.setText("");
            LastName.setFont(new Font("Nirmala UI", Font.PLAIN, 24));
            LastName.setForeground(new Color(0, 0, 0)); 
        }
    }//GEN-LAST:event_LastNameFocusGained

    private void LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusLost
        if (LastName.getText().equals("")) { 
            LastName.setText("Enter Last Name");
            LastName.setFont(new Font("Nirmala UI", Font.ITALIC, 24));
            LastName.setForeground(new Color(144, 144, 144)); 
        }
    }//GEN-LAST:event_LastNameFocusLost

    private void EmailAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddFocusGained
        if (EmailAdd.getText().equals("Enter E-mail Address")) { 
            EmailAdd.setText("");
            EmailAdd.setFont(new Font("Nirmala UI", Font.PLAIN, 24));
            EmailAdd.setForeground(new Color(0, 0, 0)); 
        }
    }//GEN-LAST:event_EmailAddFocusGained

    private void EmailAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddFocusLost
        if (EmailAdd.getText().equals("")) { 
            EmailAdd.setText("Enter E-mail Address");
            EmailAdd.setFont(new Font("Nirmala UI", Font.ITALIC, 24));
            EmailAdd.setForeground(new Color(144, 144, 144)); 
        }
    }//GEN-LAST:event_EmailAddFocusLost

    private void PhoneNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumFocusGained
        if (PhoneNum.getText().equals("Enter Phone Number")) { 
            PhoneNum.setText("");
            PhoneNum.setFont(new Font("Nirmala UI", Font.PLAIN, 24));
            PhoneNum.setForeground(new Color(0, 0, 0)); 
        }
    }//GEN-LAST:event_PhoneNumFocusGained

    private void PhoneNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumFocusLost
        if (PhoneNum.getText().equals("")) { 
            PhoneNum.setText("Enter Phone Number");
            PhoneNum.setFont(new Font("Nirmala UI", Font.ITALIC, 24));
            PhoneNum.setForeground(new Color(144, 144, 144)); 
        }
    }//GEN-LAST:event_PhoneNumFocusLost
    
    private void addMouseListenerToGoBackBtn() {
        GoBackBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                LoginPage loginPage = new LoginPage();
                loginPage.setVisible(true);
                dispose();
            }
        });
    }
    
    private void addMouseListenerToSignUpBtn() {
        SignUpBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String firstName = FirstName.getText();
                String lastName = LastName.getText();
                String emailAdd = EmailAdd.getText();
                String phoneNum = PhoneNum.getText();
                String password = new String(Password.getPassword());
                String confirmPassword = new String(ConfirmPassword.getPassword());

                StringBuilder missingFields = new StringBuilder();
                if (firstName.isEmpty() || firstName.equals("Enter First Name")) {
                    missingFields.append("First Name\n");
                }
                if (lastName.isEmpty() || lastName.equals("Enter Last Name")) {
                    missingFields.append("Last Name\n");
                }
                if (emailAdd.isEmpty() || emailAdd.equals("Enter E-mail Address")) {
                    missingFields.append("E-Mail Address\n");
                }
                if (phoneNum.isEmpty() || phoneNum.equals("Enter Phone Number")) {
                    missingFields.append("Phone Number\n");
                }
                if (password.isEmpty()) {
                    missingFields.append("Password\n");
                }
                if (missingFields.length() > 0) {
                    JOptionPane.showMessageDialog(null, "Please fill in the following fields:\n" + missingFields.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!emailAdd.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                    JOptionPane.showMessageDialog(null, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
                    EmailAdd.setText("");
                    return;
                }
                if (!password.equals(confirmPassword)) {
                    JOptionPane.showMessageDialog(null, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
                    Password.setText("");
                    ConfirmPassword.setText("");
                    return;
                }
                
                if (UserAuthenticator.signUpAccount(firstName + " " + lastName, emailAdd, phoneNum, password))
                {
                    LoginPage loginPage = new LoginPage();
                    loginPage.setVisible(true);
                    dispose();
                }
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField EmailAdd;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel GoBackBtn;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PhoneNum;
    private javax.swing.JLabel SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel1;
    private wastemanagement.components.RoundedPanel roundedPanel10;
    private wastemanagement.components.RoundedPanel roundedPanel3;
    private wastemanagement.components.RoundedPanel roundedPanel4;
    private wastemanagement.components.RoundedPanel roundedPanel5;
    private wastemanagement.components.RoundedPanel roundedPanel6;
    private wastemanagement.components.RoundedPanel roundedPanel7;
    private wastemanagement.components.RoundedPanel roundedPanel8;
    private wastemanagement.components.RoundedPanel roundedPanel9;
    // End of variables declaration//GEN-END:variables
}